[package]
name = "config"
version = "0.1.0"
edition = "2021"
authors = ["P Deepanshun"]
description = "Configuration management for VoidCLI"

[dependencies]
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
