[package]
name = "commands"
version = "0.1.0"
edition = "2021"
authors = ["P Deepanshun"]
description = "Command handling for VoidCLI"

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
anyhow = "1.0"
time = "0.3.41"

