[package]
name = "themes"
version = "0.1.0"
edition = "2021"
authors = ["P Deepanshun"]
description = "Theming system for VoidCLI"

[dependencies]
anyhow = "1.0"
lazy_static = "1.4"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"

