[package]
name = "term"
version = "0.1.0"
edition = "2021"
authors = ["P Deepanshun"]
description = "Terminal functionality for VoidCLI"

[dependencies]
anyhow = "1.0"
tokio = { version = "1.0", features = ["full"] }
nix = "0.26"
libc = "0.2"
config = { path = "../config" }
log = "0.4"

